# https://atcoder.jp/contests/abc225/tasks/abc225_a
S = input()
type_set = set()
type_set.add(S)
newS1 = "".join([S[1], S[2], S[0]])
type_set.add(newS1)
newS2 = "".join([S[2], S[0], S[1]])
type_set.add(newS2)
newS3 = "".join([S[0], S[2], S[1]])
type_set.add(newS3)
newS4 = "".join([S[1], S[0], S[2]])
type_set.add(newS4)
newS5 = "".join([S[2], S[1], S[0]])
type_set.add(newS5)
print(len(type_set))
